### DISCUSSION TITLE
Maroto Document Processor

### DISCUSSION THREAD

**Discussion by johnfercher** [johnfercher/maroto#390] [Ideas]
RFC: https://docs.google.com/document/d/1DfmeED0Nxt11bwvpZGVK51IE20sP6kCjoqQVrOSVqZE

Hello fellows, we are about to create a document processor to generate PDFs by interpreting serialized data as: yml, json or html. I know that there are projects that transform HTML to PDF, but I feel that we can do something simpler and better.

```yaml
props:
    imageHeader:
        align: center

row 10:
    col 4:
        img "https://raw.githubusercontent.com/johnfercher/maroto/master/docs/assets/images/logosmall.png" imageHeader
    col 8:
        qrcode "qrcode content"
        text "text content"
```

This is just an idea, I would like to evolve this with you.
